version: '3.5'

services:
  challenge_db:
    container_name: challenge_db
    image: postgres:9.6
    networks:
      - challenge-network
    volumes:
      - challenge-pg-data:/var/lib/postgresql/data

  challenge_web:
    container_name: challenge_web
    build : .
    ports:
      - 3000:3000
    env_file : env
    command: ["sh", "start.sh"]
    networks:
      - challenge-network
    volumes:
      - .:/challenge
      - challenge-bundle:/usr/local/bundle
    depends_on:
      - challenge_db

volumes:
  challenge-pg-data:
  challenge-bundle:

networks:
  challenge-network:
    name: challenge-network
    driver: bridge